using System.Collections.Immutable;
using System.Reflection;
using System.Text.Json;
using FFXIVAddressInfo.Shared;
using Microsoft.CodeAnalysis;

namespace FFXIVAddressInfo.SourceGeneration;

[Generator(LanguageNames.CSharp)]
internal sealed class GameAddressGenerator : ISourceGenerator
{
    private const string Tab = "    ";

    private IReadOnlyDictionary<string, DataCenterInfo>
        _addressInfo = ImmutableDictionary<string, DataCenterInfo>.Empty;

    public void Initialize(GeneratorInitializationContext context)
    {
        var assembly = Assembly.GetAssembly(typeof(GameAddressGenerator));
        var stream = assembly?.GetManifestResourceStream("FFXIVAddressInfo.SourceGeneration.data.json");
        var data = stream ?? throw new InvalidOperationException("Could not load embedded resource.");
        _addressInfo = JsonSerializer.Deserialize<IReadOnlyDictionary<string, DataCenterInfo>>(data) ??
                       ImmutableDictionary<string, DataCenterInfo>.Empty;
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var infoInit = string.Join("\n\n", _addressInfo.Values.Select(RenderDataCenterInfo).Select(c => $"    {c}"));

        //lang=c#
        var addressInfoCode = $$"""
                                // <auto-generated />
                                namespace FFXIVAddressInfo;

                                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{ToolInfo.AssemblyName}}", "{{ToolInfo.AssemblyVersion}}")]
                                public sealed partial class DataCenters
                                {
                                {{infoInit}}
                                }
                                """;

        context.AddSource("FFXIVAddressInfo.GameAddresses.GameAddresses.g.cs", addressInfoCode);
    }

    private static string RenderDataCenterInfo(DataCenterInfo info)
    {
        //lang=c#
        return
            $"""
             public static readonly global::FFXIVAddressInfo.IDataCenterAddresses {info.Name} =
             {Tab}{Tab}new global::FFXIVAddressInfo.DataCenterInfo("{info.LobbyServer}", {RenderServerAddresses(info.Addresses)});
             """;
    }

    private static string RenderServerAddresses(IEnumerable<string> addresses)
    {
        var addressInit = string.Join(", ",
                              addresses.Select(addr =>
                                  $"\n{Tab}{Tab}{Tab}" + $"""global::System.Net.IPAddress.Parse("{addr}")""")) +
                          $"\n{Tab}{Tab}";

        //lang=c#
        return $"new global::System.Net.IPAddress[] {{{addressInit}}}";
    }
}